In [4]:
!bash scripts/pretrain.sh 0 --moco --nce-k 1024



Namespace(alpha=0.999, aug='1st', batch_size=32, beta1=0.9, beta2=0.999, clip_norm=1.0, cv=False, dataset='dgl', degree_embedding_size=16, epochs=100, exp='Pretrain', finetune=False, fold_idx=0, freq_embedding_size=16, gpu=0, hidden_size=64, learning_rate=0.005, load_path=None, lr_decay_epochs=[120, 160, 200], lr_decay_rate=0.0, max_degree=512, max_edge_freq=16, max_node_freq=16, moco=True, model='gin', model_folder='saved/Pretrain_moco_True_dgl_gin_layer_5_lr_0.005_decay_1e-05_bsz_32_hid_64_samples_2000_nce_t_0.07_nce_k_1024_rw_hops_256_restart_prob_0.8_aug_1st_ft_False_deg_16_pos_32_momentum_0.999', model_name='Pretrain_moco_True_dgl_gin_layer_5_lr_0.005_decay_1e-05_bsz_32_hid_64_samples_2000_nce_t_0.07_nce_k_1024_rw_hops_256_restart_prob_0.8_aug_1st_ft_False_deg_16_pos_32_momentum_0.999', model_path='saved', momentum=0.9, nce_k=1024, nce_t=0.07, norm=True, num_copies=6, num_layer=5, num_samples=2000, num_workers=12, optimizer='adam', positional_embedding_size=32, print_freq=10, read

In [18]:
import torch
import dgl
import dgl.sparse as dglsp


indices = torch.tensor([[1, 2, 1], [2, 4, 3]])
A = dglsp.spmatrix(indices,torch.tensor([[9],[99],[19]]))
a , b , c = *A.coo() , 10
print(a,'hello',b , c)
print(A.val)
print(A.col)
print(A.row)






tensor([1, 2, 1]) hello tensor([2, 4, 3]) 10
tensor([[ 9],
        [99],
        [19]])
tensor([2, 4, 3])
tensor([1, 2, 1])


In [30]:
! bash scripts/pretrain.sh 1  --moco --nce-k 32  --num-workers 1 --num-copies 1  --dataset 'imdb-binary' --epochs 1 --num-samples 10 --rw-hops 64




========= COMPUTE-SANITIZER
Namespace(alpha=0.999, aug='1st', batch_size=32, beta1=0.9, beta2=0.999, clip_norm=1.0, cv=False, dataset='imdb-binary', degree_embedding_size=16, epochs=1, exp='Pretrain', finetune=False, fold_idx=0, freq_embedding_size=16, gpu=1, hidden_size=64, learning_rate=0.005, load_path=None, lr_decay_epochs=[120, 160, 200], lr_decay_rate=0.0, max_degree=512, max_edge_freq=16, max_node_freq=16, moco=True, model='gin', model_folder='saved/Pretrain_moco_True_imdb-binary_gin_layer_5_lr_0.005_decay_1e-05_bsz_32_hid_64_samples_10_nce_t_0.07_nce_k_32_rw_hops_64_restart_prob_0.8_aug_1st_ft_False_deg_16_pos_32_momentum_0.999', model_name='Pretrain_moco_True_imdb-binary_gin_layer_5_lr_0.005_decay_1e-05_bsz_32_hid_64_samples_10_nce_t_0.07_nce_k_32_rw_hops_64_restart_prob_0.8_aug_1st_ft_False_deg_16_pos_32_momentum_0.999', model_path='saved', momentum=0.9, nce_k=32, nce_t=0.07, norm=True, num_copies=1, num_layer=5, num_samples=10, num_workers=1, optimizer='adam', positional_emb